### ISSUE TITLE
Always Research Prior Art

### ISSUE THREAD

**Issue by ModestMC** [buddysystems/buddysystems.github.io#2]
I considered forking this to show y'all an idea when I realized I was about to suggest the Myspace model.

Ideally, someone could fork the project, create their own html page (which could also include their own css), request being added to the main list, and then submit a pull request. Provided they're reasonable, merge and you're good.

https://webring.xxiivv.com/

**Comment by CodeCricut** [comment]
Interesting idea. That would be great in case we ever expand our group to more members. We would have to tweak the layout of the homepage so that each member isn't shown in the header.

Also, what does the title of this issue mean?
